### ISSUE TITLE
HTML Element is broken 

### ISSUE THREAD

**Issue by mcmietz** [WapplerSystems/Shyguy#3]
Hi thank you for your extension. 

we try to use it in a new project with TYPO3 v10.4 and fluid_styled_content. 
After the installation it breaks the Plain Text Content Element CType = html

If you use it, your JavaScript replace the html code and the textarea is white.

**Comment by mcmietz** [comment]
https://github.com/WapplerSystems/Shyguy/blob/master/Resources/Public/Javascript/Shyguy.js 

Line 46 - 50

.replaceWith(function() {
            return this.nodeValue.replace(/(\&shy;|\­)/gi, "↵");
        });
        
        Maybe it try to render the html from textarea but it shouldn´t. 
        
        Solution would be, ignore CType=html ?

**Comment by koehnlein** [comment]
There seems to be a similar problem with HTML tags in other content elements. We have some hard coded HTML tags inside a CType=table content element.

```
foo|<b>bar</b>
foo|bar
```

When opening the backend form, the textarea is rendered as expected but immediatly replaced with new content without HTML tags and their content. So the example above becomes:

```
foo|
foo|bar
```

**Comment by koehnlein** [comment]
I spent some minutes to find more information about the problem. Thanks to @mcmietz for the hint with the code lines. The problem, I found is that ...

```js
return this.nodeValue.replace(/(\&shy;|\­)/gi, "↵");
```

... does not simply replace text, but really builds DOM and replaces the old DOM. This can be seen in action, when adding some markup to the header field:

| default behavior | with EXT:shyguy |
| --- | --- |
| ![Bildschirmfoto 2021-03-25 um 17 28 44](https://user-images.githubusercontent.com/16088567/112508628-05f9dc00-8d90-11eb-8201-a00aefbab013.png) | ![Bildschirmfoto 2021-03-25 um 17 30 52](https://user-images.githubusercontent.com/16088567/112508667-0c885380-8d90-11eb-87bc-e5b74a6eea9a.png) |

I think the solution would be to replace the html special characters in the string before returning the value.

**Comment by mcmietz** [comment]
I tested your fix in our case and it looks good, also seems to be the solution for our problem. 

Thanks a lot
